# Generated by Django 2.0 on 2019-02-19 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_image'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='first_user',
        ),
        migrations.AddField(
            model_name='thread',
            name='first_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to='account.Profile'),
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second_user',
        ),
        migrations.AddField(
            model_name='thread',
            name='second_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to='account.Profile'),
        ),
    ]
